create or replace function public.is_current_user_admin_or_supervisor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.user_roles ur on ur.profile_id = p.id
    where p.auth_user_id = auth.uid()
      and p.account_status = 'approved'
      and ur.role in ('admin', 'supervisor')
  );
$$;

grant execute on function public.is_current_user_admin_or_supervisor() to authenticated;

create table public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  item_code text,
  name text not null,
  unit text not null,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index inventory_items_name_idx on public.inventory_items (name);
create unique index inventory_items_item_code_unique_idx
on public.inventory_items (item_code)
where item_code is not null;

create table public.stock_locations (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  name text not null,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index stock_locations_code_unique_idx on public.stock_locations (code);
create index stock_locations_name_idx on public.stock_locations (name);

create table public.stock_admin_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in (
      'inventory_item_created',
      'inventory_item_updated',
      'stock_location_created',
      'stock_location_updated'
    )
  ),
  entity_type text not null check (entity_type in ('inventory_item', 'stock_location')),
  entity_id uuid not null,
  actor_auth_user_id uuid references auth.users (id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index stock_admin_events_entity_idx on public.stock_admin_events (entity_type, entity_id, created_at desc);

create trigger inventory_items_set_updated_at
before update on public.inventory_items
for each row
execute function public.set_current_timestamp_updated_at();

create trigger stock_locations_set_updated_at
before update on public.stock_locations
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.inventory_items enable row level security;
alter table public.stock_locations enable row level security;
alter table public.stock_admin_events enable row level security;

create policy "inventory_items_select_approved"
on public.inventory_items
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.auth_user_id = auth.uid()
      and p.account_status = 'approved'
  )
);

create policy "inventory_items_insert_operational"
on public.inventory_items
for insert
to authenticated
with check (public.is_current_user_admin_or_supervisor());

create policy "inventory_items_update_operational"
on public.inventory_items
for update
to authenticated
using (public.is_current_user_admin_or_supervisor())
with check (public.is_current_user_admin_or_supervisor());

create policy "stock_locations_select_approved"
on public.stock_locations
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.auth_user_id = auth.uid()
      and p.account_status = 'approved'
  )
);

create policy "stock_locations_insert_operational"
on public.stock_locations
for insert
to authenticated
with check (public.is_current_user_admin_or_supervisor());

create policy "stock_locations_update_operational"
on public.stock_locations
for update
to authenticated
using (public.is_current_user_admin_or_supervisor())
with check (public.is_current_user_admin_or_supervisor());

create policy "stock_admin_events_select_approved"
on public.stock_admin_events
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.auth_user_id = auth.uid()
      and p.account_status = 'approved'
  )
);

create policy "stock_admin_events_insert_operational"
on public.stock_admin_events
for insert
to authenticated
with check (public.is_current_user_admin_or_supervisor());
