create type public.account_status as enum ('pending', 'approved', 'disabled');

create type public.app_role as enum ('admin', 'supervisor', 'operator');

create table public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  email text not null,
  full_name text,
  account_status public.account_status not null default 'pending',
  onboarding_source text not null default 'self_registration' check (
    onboarding_source in ('self_registration', 'invitation', 'admin_provisioned')
  ),
  invited_by_auth_user_id uuid references auth.users (id) on delete set null,
  invited_at timestamptz,
  approved_at timestamptz,
  disabled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index profiles_email_lower_unique_idx
on public.profiles (lower(email));

create index profiles_auth_user_id_idx on public.profiles (auth_user_id);
create index profiles_account_status_idx on public.profiles (account_status);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  role public.app_role not null,
  created_by_auth_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (profile_id, role)
);

create index user_roles_profile_id_idx on public.user_roles (profile_id);
create index user_roles_role_idx on public.user_roles (role);

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;

create policy "profiles_select_own"
on public.profiles
for select
using (auth.uid() = auth_user_id);

create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = auth_user_id);

create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

create policy "user_roles_select_own"
on public.user_roles
for select
using (
  exists (
    select 1
    from public.profiles p
    where p.id = user_roles.profile_id
      and p.auth_user_id = auth.uid()
  )
);